    name: Python Setup

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4 # Checkout the repository code

        - name: Set up Python
          uses: actions/setup-python@v4 # Setup a specific Python version
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest # Install flake8 and pytest
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt # Install other dependencies from requirements.txt if present
            fi

        - name: Lint with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

        - name: Test with pytest
          run: |
            pytest tests/test_mod.py::TestClass::test_method
